### PR TITLE
add property 'blurSuperView'

### PR DESCRIPTION
**Pull request by ChrisXu**
Hi, I use this in my component which is a custom alert view.
And my problem is,  when I show the alert view, actually it was created on another window.
Therefore I add a new property `blurSuperView`. When `refresh` been call, it check if blurSuperView had been set to other view. if not, use superview as backgroundView.

Hope this is useful for others.

### CODE REVIEW

**Comment by evadne** [comment]
Maybe a better way is to specify the image source?

**Comment by ghost** [comment]
I feel like this needs some more thought.

First problem is, I don't like how this code is written in -refresh. It's checking the ivar -blurSuperView twice on each iteration of -refresh. Not very clean. (and I realize I'm being picky here.)

Second problem is, for what you're doing here, is there a reason why you can't change this LFGlassView's superview so that it gets moved over to the custom alert view?

Granted, you have your own fork and you can do whatever you want with it, but I feel like there's not enough here to justify adding another ivar and another conditional statement for a completely optional property that will confuse people a bit.

Take this scenario, what if the LFBlurView is right between two views? If we choose this solution, we still have to pick only one view to blur from. And if we go with the solution we have today, only the view declared as this LFGlassView instance's superview gets blurred. So, no advantage here.

Based on that, I don't think this solution you've proposed improves enough upon our current superview based solution. There's flaws, yes, and I'm aware of how things can break down with -renderInContext: for certain kinds of layers. But we need something that can cover more scenarios, and stay fast.

Thanks for your contribution, though. I do appreciate that you're enjoying our work.

**Comment by evadne** [comment]
@nglevin I understand your concerns with this patch.

@ChrisXu1221 thanks for your contribution and I’d like to see you resubmit. In order to do that please let me know…

a) Are you interested in having `LFGlassView` source its image from a view in another window?
b) @nglevin did mention that you’re heckling `blurSuperView` within the drawing code. This warrants its own paragraph —

If you use `-[UIView didMoveToSuperview]` and dynamically select the blurring source view there, it’s fine, but then you’re doing magic. Even if you end up with something like `-[LFGlassView initWithFrame:sourceView:]` you’re going to break a formal contract where `LFGlassView` simply blurs whatever view that contains it which can be changed at any time.

So unfortunately I think we are indeed not pulling it in its current state. However if you try [ios-blur](https://github.com/JagCesar/iOS-blur‎) it might just work for your scenario.

**Comment by ChrisXu** [comment]
@nglevin , @evadne  Thanks, I got it :)

My question is what if the keyWindow  is changed or current viewController is popped out, and I want the blurView still show on the screen?

**Comment by evadne** [comment]
You could possibly just make a new one. (I’m not entirely sure.)

**Comment by evadne** [comment]
@ChrisXu1221 I just realized — are you trying to make [CXAlertView](https://github.com/ChrisXu1221/CXAlertView) with this project? In that case you have a valid point. If you send me a commit which demonstrates your use of LiveFrost, I can take a look at it.

**Comment by ChrisXu** [comment]
Sure :) Wait me a min.

**Comment by ghost** [comment]
@evadne I remember you told me that you were thinking of implementing a similar feature yourself with an optional delegate callback. Is this still something that you are working on?

**Comment by evadne** [comment]
Yep

**Comment by JaviSoto** [comment]
+1

**Comment by ghost** [comment]
@evadne is very sick at the moment.

I'd like to get this issue resolved, though, so I'll bring it up again when she's feeling better. Or if she'd be interested in having me take a look at this.

If you happen to have any suggestions about design, please let us know.

**Comment by evadne** [comment]
Please go wild on this @nglevin I think we have been trying to find the one true form for too long.

(I should not be here.)

**Comment by ghost** [comment]
Okay, I'll have a look and talk over ideas this weekend.

Between now and when this PR was put out, I sat down with @evadne to talk about this. I'm clearer on why @ChrisXu1221 wanted this feature, and it's a really good one.

Now, If there are some other potential uses for this feature that can be shared, I'd also like to hear about them. At least, it'd help me figure out the problems to be solved, rather than obsess over implementation details.

**Comment by ghost** [comment]
There is one big problem with introducing a feature like this, and it's how we translate the `frame` of the target view.

Specifically, what happens when the `LFGlassView` instance is trying to figure out where its frame lies relative to the coordinate space of the target view's frame, when the view isn't within the same view hierarchy as the `UIWindow` object. From the [developer documentation](https://developer.apple.com/library/ios/documentation/uikit/reference/uiview_class/uiview/uiview.html#//apple_ref/occ/instm/UIView/convertRect:fromView:) for `-convertRect:fromView:`,

> both view and the receiver must belong to the same `UIWindow` object.

For @ChrisXu1221 's specific case in `CXAlertView`, he's managing two different `UIWindow` objects, one of which contains an instance of the `LFGlassView` that's impressively made to look like the iOS 7 `UIAlertView`, and another which contains the app's original view hierarchy.

For this particular case, this is not a problem because these `UIWindow`s are the same size and the alert we see centers itself in the middle of the screen. One `UIWindow` comes from `[[UIApplication sharedApplication] keyWindow]` and the other one is a brand new `UIWindow` initialized with the frame `[[UIScreen mainScreen] bounds]`.

However, if we want this to be a feature that can be used for a wider range of purposes, we need to be able to figure out what subset of the target view we'd like to draw and blur within a CoreGraphics object. And if the target view or layer can be literally _anything_, we have to sacrifice some automation there.

I don't want the user of this object to have to provide a custom `CGPoint` to define how the `LFGlassView` instance should be offset relative to the target view's `bounds`, it's a really ugly requirement. But if we want to work with any view or layer, we can't get the information we need from the `frame` ivar any longer, and not even `-convertRect:fromView:` will help us there.

This is why I'd like some idea of what some users want this feature for. Because that does affect the design, here, and it's the difference between a nice API and an ugly as sin workaround.

**Comment by ghost** [comment]
Let me know if this sounds too crazy.

I think the next big step for LiveFrost would be to split up the `UIView` based design to a `UIView` and `CALayer` interface, with the `UIView` covering the most common cases. The `CALayer` subclass would have the support code we need to get the blurring to work with animations, and most of the bits doing all the work in the `UIView` subclass right now.

So where do we put in an interface for a custom, target layer to base our blur from?

I believe that the `CALayer` subclass makes the most sense here, and there we can add more customization options that aren't exposed from the `UIView` itself. If we do want to tackle blurring layers that aren't even in the same layer tree, like in @ChrisXu1221 's case, we'll probably have defaults that cover the common "derive placement based on frames" case, and also provide an override that allows developers to define a `center` for blurring (a `CGPoint`) based on the target layer's coordinate space (`bounds`).

This would be possible to automate to some degree if there was an easy way of telling if two views belong to the same view tree, or two layers belong to the same layer tree. Unfortunately, there doesn't seem to be one besides walking up and down the view/layer hierarchy of one view/layer, and comparing references to views in the tree to see if one matches the other. That can be quite time consuming, so it's probably not worth adding that feature. Relying on the presence of an override seems to be the fastest, and less obnoxious way to do this.

There are some deeper questions about how this would look and work that I'm not ready to answer just yet. I'll have to work on the `CALayer` based version some more, see what new problems I encounter, and keep this feature in mind while I do so.

**Comment by ghost** [comment]
Closing the PR, but I'll leave the issue open.

**Pull request closed without merging**
