### PR TITLE
Blends with backgroundColor

### PR DESCRIPTION
**Pull request by kennic**
backgroundColor is now blended with blurred image

### CODE REVIEW

**Comment by ghost** [comment]
I'm in the middle of two big projects, so I apologize for leaving this in the dark for a week, now.

I think the code looks good, my first concern is that it's doing a CPU-intensive task in the one method that gets called the most during rendering. I'd be interested to see how this code would benchmark against an alternate implementation that has transparent, colored CALayer rendered on top of or underneath this view to handle this task. The CALayer based blend would leverage the GPU to some degree, which is generally much better suited for compositing bitmap images. The Core Graphics methods, by comparison, use the CPU, but they sometimes leverage some of the darker corners of the device like ARM NEON for fast math.

Second is, I'd like to be able to turn this blending off by default, just to keep things fast and avoid doing unnecessary work when a developer doesn't need to use this effect.

Last, I'm curious if `tintColor` would be a better place to have a feature like this. But the more that I think about the intent of iOS 7's `tintColor`, I think `backgroundColor` is probably the better choice.

**Comment by evadne** [comment]
What happens if you put the glass view in a super view of the same
dimensions with a sibling beneath the glass view holding a semitransparent
background color?

Best,
Eve

On Mar 15, 2014, at 13:17, Nicholas Gabriel Levin notifications@github.com
wrote:

I'm in the middle of two big projects, so I apologize for leaving this in
the dark for a week, now.

I think the code looks good, my first concern is that it's doing a
CPU-intensive task in the one method that gets called the most during
rendering. I'd be interested to see how this code would benchmark against
an alternate implementation that has transparent, colored CALayer rendered
on top of or underneath this view to handle this task. The CALayer based
blend would leverage the GPU to some degree, which is generally much better
suited for compositing bitmap images. The Core Graphics methods, by
comparison, use the CPU, but they sometimes leverage some of the darker
corners of the device like ARM NEON for fast math.

Second is, I'd like to be able to turn this blending off by default, just
to keep things fast and avoid doing unnecessary work when a developer
doesn't need to use this effect.

Last, I'm curious if tintColor would be a better place to have a feature
like this. But the more that I think about the intent of iOS 7's tintColor,
I think backgroundColor is probably the better choice.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/radi/LiveFrost/pull/17#issuecomment-37717746
.

**Comment by kennic** [comment]
You're right, blending color using my method is a CPU-intensive task. I will rewrite it. Thanks for your feedback.

**Comment by kennic** [comment]
I just updated it, performace improved by using CALayer,  please take a look.

**Comment by ghost** [comment]
Thanks, I'll have a look at this tomorrow.

**Comment by ghost** [comment]
Hum. I didn't want this issue closed as I wanted to do a small writeup on the changes I made. I guess Github detected that I manually merged your code and decided to be too convenient.

Writeup forthcoming. I need a coffee, first.

**Comment by ghost** [comment]
I'll explain the changes I made in the order they were mentioned in 6cadc8e771b1f63602c2c8711aeb43e5c2280f23 ...
- I've given you credit in the license file and in the LFGlassView source and header files, and the license file.
- I moved the allocation of the layer that handles the background color into `-setup`, the method that gets called when the layer's initialized.

This is based on an implementation detail of CALayer that is not well documented, to my knowledge. If you create a new layer in a UIView's `-drawRect:`, it uses MUCH more CPU when rendering than if you created that layer anywhere else. For instance, in UIView's `-layoutSubviews`.

...Though, frankly, the best approach is to create layers when a UIView is initialized, or when some method is invoked that makes it clear that you'll need those layers later for rendering. To keep things really fast for events such as rotation, `-layoutSubviews` should only be used to assign frames, bounds, and centers, it's not a place where objects should be created. Nonetheless, it's better than `-drawRect:`. My point is, `-drawRect:` has side effects on layers and you shouldn't create layers there.

My concern is that someone might assign a `backgroundColor` in `-drawRect:`, and that would trip off an unexpected performance penalty. On the other hand, creating a layer is inexpensive, and keeping it in memory when we don't need it is also inexpensive. So I created that layer when the LFGlassView is initialized.
- Rather than use a boolean ivar to regulate when the `backgroundColor` should be used, I took it out in favor of an approach that adds the layer with the `backgroundColor` to the LFGlassView's layer tree when a `backgroundColor` is assigned that has an alpha channel that's greater than 0.

That eliminates an extra ivar, to keep the number of ivars to a minimum. I've had experience with bad codebases that had 20+ BOOLean ivars with purposes that weren't clear, that sometimes didn't trip off properly when needed, so I tend to try to stay lean on those. Instead, I try to query the source when possible. (Call it a form of PTSD.)

It also means when the `backgroundColor` indicates that it should be invisible, we don't put that colored layer in place. I think that's a pretty solid means of determining when to use this feature.
- The frame for this new layer gets adjusted when the image buffers that serve as our rendering surfaces for the blur need to be adjusted.

It's more or less a means of keeping things DRY. The name of that private method was also changed in a later commit to indicate that the layer will get adjusted on frame changes.

If you have any other questions, let me know. I'll push this feature up to `master` and update CocoaPods with these changes on Friday.

**Comment by kennic** [comment]
great work! thanks a lot for your improvement. Keep it up!

**Comment by FitnessMobile** [comment]
hi, does this feature add color to blur effect when the glass view has background color? Like ios transculant does on certain views ?

**Pull request merged**
