### PR TITLE
Use correct URLs in podspec

### PR DESCRIPTION
**Pull request by getaaron**
Not sure if you want this in `develop` along with the other stuff.  Cocoapods needs the HTTPS URL.

### CODE REVIEW

**Comment by getaaron** [comment]
I also submitted this updated podspec to Cocoapods, and it was approved: https://github.com/CocoaPods/Specs/pull/5539

**Comment by evadne** [comment]
Looks like I have no other option than to merge it, eh?

On Nov 20, 2013, at 5:22 AM, Aaron Brager notifications@github.com wrote:

I also submitted this updated podspec to Cocoapods, and it was approved:
CocoaPods/Specs#5539 https://github.com/CocoaPods/Specs/pull/5539

—
Reply to this email directly or view it on
GitHubhttps://github.com/radi/LiveFrost/pull/8#issuecomment-28836864
.

**Comment by ghost** [comment]
We probably would want this to reference the master branch at some point, since master should be reserved for releases. Not develop.

**Comment by evadne** [comment]
Agreed. We should tag master and tag 0.0.3. Then we should push a new pod.
Concur?

On Nov 20, 2013, at 10:53, Nicholas Gabriel Levin notifications@github.com
wrote:

We probably would want this to reference the master branch at some point,
since master should be reserved for releases. Not develop.

—
Reply to this email directly or view it on
GitHubhttps://github.com/radi/LiveFrost/pull/8#issuecomment-28859871
.

**Comment by ghost** [comment]
Sounds like a plan.

**Pull request merged**
